augmentation_pipeline:
  train:
    - transform: HorizontalFlip
      args:
        p: 0.5
    - transform: VerticalFlip
      args:
        p: 0.5
    - transform: OneOf
      args:
        transforms:
          - transform: RandomBrightnessContrast
            args: 
              brightness_limit: 0.2  # Adjust these values as needed
              contrast_limit: 0.2    # Adjust these values as needed
              p: 0.5
          - transform: RandomGamma
            args: 
              gamma_limit: (80, 120)  # 100 is no change
              p: 0.5
        p: 0.3
    - transform: OneOf
      args:
        transforms:
          - transform: ElasticTransform
            args:
              alpha: 120
              sigma: 6  # 120 * 0.05
              alpha_affine: 3.6  # 120 * 0.03
              p: 0.5
          - transform: GridDistortion
            args:
              num_steps: 5  # Default is 5, adjust as needed
              distort_limit: 0.3  # Adjust based on the desired level of distortion
              p: 0.5
          - transform: OpticalDistortion
            args:
              distort_limit: 2
              shift_limit: 0.5
              p: 0.5
        p: 0.3
