
[project]
name = "automedlabel"
version = "0.1.0"
description = "A reproducible pipeline for evaluating foundation models in musculoskeletal MRI."
authors = [
    {name = "Gabrielle Hoyer", email = "gabbie.hoyer@ucsf.edu"}
]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"

# Main dependencies 
dependencies = [
    "numpy>=1.23.0,<=2.1.1",
    "pandas>=1.1.4",
    "torch>=1.8.0",
    "opencv-python>=4.6.0",
    "tqdm>=4.64.0",
    "matplotlib>=3.3.0",
    "scikit-image",
    "scikit-learn",
    "scipy>=1.4.1"
]

[project.optional-dependencies]
segmentation = [
    "monai",
    "albumentations",
    "pycocotools",
    "torchvision>=0.9.0",
]
preprocessing = [
    "cc3d",
    "pyarrow",
    "pydicom",
    "pyrootutils"
]
notebooks = [
    "IPython",
    "jupyter"
]
statistics = [
    "pingouin",
    "rich",
    "seaborn>=0.11.0",
    "statsmodels"
]
object_detection = [
    "clearml",
    "comet_ml",
    "coremltools",
    "py-cpuinfo",
    "dataset",
    "dill",
    "duckdb",
    "dvc",
    "dvclive",
    "mlflow",
    "mss",
    "neptune",
    "nncf",
    "onnx",
    "onnxruntime",
    "onnxsim",
    "openai",
    "openvino",
    "paddle",
    "psutil",
    "ray[tune]",
    "requests>=2.23.0",
    "rtdetr",
    "sentry_sdk",
    "shapely",
    "super_gradients",
    "tensorboard",
    "tensorflow",
    "tensorflowjs",
    "tensorrt",
    "tflite_runtime",
    "tflite_support",
    "tritonclient",
    "ultralytics-thop>=2.0.0",
    "x2paddle",
    "yt_dlp"
]
sam = [
    "Pillow>=7.1.2",
    "hydra-core",
    "omegaconf"
]

[project.scripts]
automedlabel = "src.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
