


# ------------------------ Evaluation ------------------------ #
evaluation:
  name: "DHAL_Shoulder_SAM2_mem"
  description: "Evaluating models finetuned on the DHAL shoulder MRI dataset."

SEED: 42
distributed: False

dataset:
  DHAL-cube:
    config: DHAL.yaml       # DHAL-Evaluation
    project: DHAL-Evaluation

datamodule:
  max_subject_set: 3
  bbox_shift: 0
  batch_size: 1  
  num_workers: 1

module:
  work_dir: "work_dir/evaluation"
  task_name: DHAL-Evaluation
  use_wandb: True
  visualize: True

output_configuration:
  save_path: Run_Summaries
  viz_eval_path: ${output_configuration.save_path}/figs
  summary_file: ${evaluation.name}_data_summary.csv
  logging_level: INFO 

# base_model: "work_dir/model_weights/MedSAM/medsam_vit_b.pth"
# "work_dir/model_weights/SAM/sam_vit_b_01ec64.pth"

base_model: "work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt"
# base_model: "work_dir/model_weights/SAM2/sam2_hiera_tiny.pt"
# base_model: "work_dir/model_weights/SAM/sam_vit_b_01ec64.pth"

models:

  - finetuned_model: /data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/finetuning/DHAL-Shoulder/SAM2_mem_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240819-0105_finetuned_model_best_converted.pth
    model_weights: DHAL_SAM2_mem-bal_False-sub_set_full-bbox_shift_0
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: true
      mask_decoder: true

  # - finetuned_model: "/data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_False_maskDec_True/Run_1/20240816-0132_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_0
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: false
  #     mask_decoder: true
  # - finetuned_model: "/data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_False_maskDec_True/Run_2/20240816-2151_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_5
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 5
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: false
  #     mask_decoder: true
  # - finetuned_model: "/data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/finetuning/DHAL-Shoulder/SAM2_mem_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240819-0105_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_0
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: true
  #     mask_decoder: true
  # - finetuned_model: "/data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240815-2251_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_0
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: true
  #     mask_decoder: true
  # - finetuned_model: "/data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_2/20240816-1227_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_5
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 5
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: true
  #     mask_decoder: true
