
# ------------------------ Evaluation ------------------------ #
evaluation:
  name: "DHAL_Shoulder_SAM2_mem"
  description: "Evaluating models finetuned on the DHAL shoulder MRI dataset."

SEED: 42
distributed: False

dataset:
  DHAL-cube:
    config: DHAL.yaml      
    project: DHAL-Evaluation  # useful for stating Weights and Biases project name if user want to use w&b

datamodule:
  max_subject_set: 3  # if the user wants to test eval pipeline functionality with small subset, though the 'full' test set will automatically be run in addition to this
  bbox_shift: 0  # eval doesnt typically include augmentation, however, if goal is automatic YOLO + SAM model, this shifting may be a realistic gauge of what your model can handle for inference
  batch_size: 1  
  num_workers: 1

module:
  work_dir: "work_dir/evaluation"
  task_name: DHAL-Evaluation
  use_wandb: True
  visualize: True

output_configuration:
  save_path: Run_Summaries
  viz_eval_path: ${output_configuration.save_path}/figs
  summary_file: ${evaluation.name}_data_summary.csv
  logging_level: INFO 

base_model: "work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt"
# base_model: "work_dir/model_weights/SAM2/sam2_hiera_tiny.pt"

models:
  - finetuned_model: /work_dir/finetuning/DHAL-Shoulder/SAM2_mem_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240819-0105_finetuned_model_best_converted.pth
    model_weights: DHAL_SAM2_mem-bal_False-sub_set_full-bbox_shift_0
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: true
      mask_decoder: true

  # - finetuned_model: "/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_False_maskDec_True/Run_1/20240816-0132_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_0
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: false
  #     mask_decoder: true
  # - finetuned_model: "/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_False_maskDec_True/Run_2/20240816-2151_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_5
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 5
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: false
  #     mask_decoder: true
  # - finetuned_model: "/work_dir/finetuning/DHAL-Shoulder/SAM2_mem_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240819-0105_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_0
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: true
  #     mask_decoder: true
  # - finetuned_model: "/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240815-2251_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_0
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: true
  #     mask_decoder: true
  # - finetuned_model: "/work_dir/finetuning/DHAL-Shoulder/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_2/20240816-1227_finetuned_model_best_converted.pth"
  #   model_weights: DHAL_SAM2-bal_False-sub_set_full-bbox_shift_5
  #   sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 5
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: true
  #     mask_decoder: true
