
# ------------------------ Evaluation ------------------------ #
evaluation:
  name: "OAI_Knee_SAM2"
  description: "Evaluating models finetuned on the OAI Knee MRI dataset."

SEED: 42
distributed: False

dataset:
  OAI-imorphics:
    config: OAI_imorphics.yaml      
    project: OAI-imorphics-Evaluation

  # ** Can evaluate model on out-of-distribution knee sets not included in finetuning **:
  # TBrecon:
  #   config: TBrecon.yaml            
  #   project: TBrecon-Evaluation
  # P50-MAPSS:
  #   config: P50_compart.yaml        
  #   project: P50-Evaluation
  # AFCL-MAPSS:
  #   config: AFACL_compart.yaml      
  #   project: AFACL-Evaluation
  # K2S-cube:
  #   config: K2S.yaml              
  #   project: K2S-Evaluation

datamodule:
  max_subject_set: 3
  bbox_shift: 0
  batch_size: 1  
  num_workers: 1

module:
  work_dir: "work_dir/evaluation"
  task_name: Knee-Evaluation
  use_wandb: True
  visualize: True

output_configuration:
  save_path: Run_Summaries
  viz_eval_path: ${output_configuration.save_path}/figs
  summary_file: ${evaluation.name}_data_summary.csv
  logging_level: INFO 

base_model: "work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt"
# base_model: "work_dir/model_weights/SAM2/sam2_hiera_tiny.pt"

models:
  - finetuned_model: /work_dir/finetuning/OAI-Knee/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_False_maskDec_True/Run_1/20240816-0253_finetuned_model_best_converted.pth
    model_weights: OAI_Knee_SAM2-bal_False-sub_set_full-bbox_shift_0
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: false
      mask_decoder: true
  - finetuned_model: /work_dir/finetuning/OAI-Knee/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_False_maskDec_True/Run_4/20240817-2208_finetuned_model_best_converted.pth
    model_weights: OAI_Knee_SAM2-bal_False-sub_set_full-bbox_shift_5
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 5
    trainable:
      prompt_encoder: false
      image_encoder: false
      mask_decoder: true
  - finetuned_model: /work_dir/finetuning/OAI-Knee/SAM2_mem_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_2/20240819-0440_finetuned_model_best_converted.pth
    model_weights: OAI_Knee_SAM2-bal_False-sub_set_full-bbox_shift_0
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: true
      mask_decoder: true
  - finetuned_model: /work_dir/finetuning/OAI-Knee/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240815-2251_finetuned_model_best_converted.pth
    model_weights: OAI_Knee_SAM2-bal_False-sub_set_full-bbox_shift_0
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: true
      mask_decoder: true
  - finetuned_model: /work_dir/finetuning/OAI-Knee/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_2/20240816-1438_finetuned_model_best_converted.pth
    model_weights: OAI_Knee_SAM2-bal_False-sub_set_full-bbox_shift_5
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 5
    trainable:
      prompt_encoder: false
      image_encoder: true
      mask_decoder: true
