names:
- epiglottis
- vocal cords
- arytenoid
- trachea rings
- esophagus
- introducer
- endotracheal tube
- balloon
- blood
- NG tube
- unknown

nc: 11

# path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/detection/VLS/AirDet/datasets/preprocessed_data/yolo_format
path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/preprocessed_data/yolo_format

train: train/images
val: train/images
test: test/labels


# # options for yaml design: https://github.com/ultralytics/ultralytics/issues/8254