# might need to include background as an option, loools b/c masks include this unique val, else out of bounds index eventually

names:
- background
- sc_fat
- fascia
- extensors
- hamstrings
- fem_cortex
- fem_bm
- adductors
- sartorius
- gracilis
- nv

nc: 11

# path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/detection/VLS/AirDet/datasets/preprocessed_data/yolo_format
# path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/thigh_npy
# path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/thigh_npy3
path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/thigh_npy3_instance

# temp test func
train: train/images
val: train/images
test: test/labels



# BTW *.npy files are only generated if you use cache=disk during training. By default these are not generated.

# suggestions for how to approach custom npy dataset for YOLO :,D
# https://github.com/ultralytics/ultralytics/issues/8199


# # options for yaml design: https://github.com/ultralytics/ultralytics/issues/8254


# mask_labels:
#   0: background  # just added for finetune_evaluate...
#   1: sc_fat
#   2: fascia      # currently removing this from finetuning b/c it creates so many bboxes that cuda memory error takes place
#   3: extensors
#   4: hamstrings
#   5: fem_cortex
#   6: fem_bm
#   7: adductors
#   8: sartorius
#   9: gracilis
#   10: nv