
# ------------------------ Evaluation ------------------------ #
evaluation:
  name: "OAI_T1_Thigh_multiclass_biomarker"
  description: "Evaluating models finetuned on MSK MRI dataset for potential in downstream biomarker computation."

SEED: 42
distributed: False 

dataset:
  OAI-thigh:
    config: OAI_T1_Thigh.yaml       
    project: multiclass_Thigh-Evaluation

datamodule:
  max_subject_set: 5
  bbox_shift: 0
  batch_size: 1  
  num_workers: 1
  metric:
    func:
      tissuevolume: true
    tissues: [3, 4, 5, 6, 7, 8, 9]
    dicom_fields: ['pixel_spacing', 'slice_thickness', 'rows', 'columns']
    representative_slice: False

module:
  work_dir: "work_dir/evaluation"
  task_name: multiclass_Thigh-Evaluation
  use_wandb: True
  visualize: True

output_configuration:
  save_path: Run_Summaries
  viz_eval_path: ${output_configuration.save_path}/figs
  summary_file: ${evaluation.name}_data_summary.csv
  logging_level: INFO 

# base_model: "work_dir/model_weights/MedSAM/medsam_vit_b.pth"
base_model: "work_dir/model_weights/SAM/sam_vit_b_01ec64.pth"

# base_model: "work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt"

# note: these are all no-fascia
models:
    
    # best for muscle:
  - finetuned_model: /data/mskprojects/mskSAM/users/ghoyer/mskSam/work_dir/model_weights/Finetuned/Muscle/no_aug_bbox_shift_0/not_balanced/img_enc_True/early_stop_patience_10/subject_full/20240530-0438_finetuned_model_best.pth
    model_weights: mixed_Muscle_SAM-bal_False-sub_set_full-bbox_shift_0
    # sam2_model_cfg: sam2_hiera_b+.yaml
    model_type: vit_b
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: false
      mask_decoder: true

  #   #best for bone:
  # - finetuned_model: /data/mskprojects/mskSAM/users/ghoyer/mskSam/work_dir/model_weights/Finetuned/OAI_Thigh/no_aug_bbox_shift_0/multi_class_model/img_enc_True/early_stop_patience_10/subject_full/20240522-1945_finetuned_model_best.pth

  #   model_weights: Thigh_multiclass_SAM-bal_False-sub_set_full-bbox_shift_0
  #   # sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_type: vit
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: false
  #     mask_decoder: true

  # best for fat:

  # - finetuned_model: /data/mskprojects/mskSAM/users/ghoyer/mskSam/work_dir/finetuning/mskSAM/MedSAM_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240809-0046_finetuned_model_best_converted.pth
  #   model_weights: mskSAM_MedSAM-bal_False-sub_set_full-bbox_shift_0
  #   # sam2_model_cfg: sam2_hiera_b+.yaml
  #   model_type: vit
  #   model_details:
  #     balanced: false
  #     subject: full
  #     bbox_shift: 0
  #   trainable:
  #     prompt_encoder: false
  #     image_encoder: false
  #     mask_decoder: true