
# ------------------------ Evaluation ------------------------ #
evaluation:
  name: "OAI_Knee_biomarker"
  description: "Evaluating models finetuned on MSK MRI dataset for potential in downstream biomarker computation."

SEED: 42
distributed: False

dataset:
  OAI-imorphics:
    config: OAI_imorphics.yaml      
    project: OAI-imorphics-Evaluation

datamodule:
  max_subject_set: 3
  bbox_shift: 0
  batch_size: 1  
  num_workers: 1
  metric:
    func:
      cartilagethickness: true
    tissues: [1, 2, 3, 4]   
    dicom_fields: ['pixel_spacing', 'slice_thickness', 'rows', 'columns']
    representative_slice: True

module:
  work_dir: "work_dir/evaluation"
  task_name: Knee-Evaluation
  use_wandb: False #True
  visualize: False #True

output_configuration:
  save_path: Run_Summaries
  viz_eval_path: ${output_configuration.save_path}/figs
  summary_file: ${evaluation.name}_data_summary.csv
  logging_level: INFO 

base_model: "work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt"

models:
    # best cartilage model
  - finetuned_model: /work_dir/finetuning/OAI-Knee/SAM2_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_1/20240815-2251_finetuned_model_best_converted.pth

    model_weights: OAI_Knee_SAM2-bal_False-sub_set_full-bbox_shift_0
    sam2_model_cfg: sam2_hiera_b+.yaml
    model_details:
      balanced: false
      subject: full
      bbox_shift: 0
    trainable:
      prompt_encoder: false
      image_encoder: true
      mask_decoder: true