names:
- background
- scapula

nc: 2

path: /data/mskscratch/users/ghoyer/shoulder_pipeline/standardized_shoulder/DHAL/shoulder/T2/npy/YOLO

train: train/images
# val: val/images
val: train/images
test: test/images

meta_path: /data/mskscratch/users/ghoyer/shoulder_pipeline/standardized_shoulder/DHAL/shoulder/T2/metadata/volume_metadata_for_ml.json

