names:
- background
- femoral cartilage
- lateral tibial cartilage
- medial tibial cartilage
- patellar cartilage
- lateral meniscus
- medial meniscus

nc: 7

path: /knee_pipeline/standardized_knee/OAI/knee/3D_DESS/Imorphics/npy/YOLO

train: train/images
val: val/images
test: test/images

# in development
# meta_path: /standardized_knee/OAI/knee/3D_DESS/Imorphics/metadata/volume_metadata_for_ml.json 

