nc: 28

path: /lumbar_spine/T1_sag/npy/YOLO

train: train/images
val: val/images
test: test/images

meta_path: /lumbar_spine/T1_sag/metadata/volume_metadata_for_ml.json 

names:
- background
- L5
- L4-L5
- L4
- L3-L4
- L3
- L2-L3
- L2
- L1-L2
- L1
- T12-L1
- T12
- L5-S1
- S1
- T11-T12
- T11
- S1-S2
- S2
- T10-T11
- T10
- S2-S3
- S3
- T9-T10
- T9
- S3-S4
- S4
- T8-T9
- T8

