names:
- background
- sc_fat
- fascia
- extensors
- hamstrings
- fem_cortex
- fem_bm
- adductors
- sartorius
- gracilis
- nv

nc: 11

path: /path/to/AutoMedLabel/standardized_data/thigh/yolo

train: train/images
val: val/images
test: test/images

# meta_path: /path/to/AutoMedLabel/standardized_data/thigh/metadata/volume_metadata_for_ml.json 

