names:
- background
- sc_fat
- fascia
- extensors
- hamstrings
- fem_cortex
- fem_bm
- adductors
- sartorius
- gracilis
- nv

nc: 11

path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/yolo_square_resized

train: train/images
val: val/images
test: test/images

# future development
# meta_path: /data/bigbone3/ghoyer/standardized/OAI/thigh/T1_ax/metadata/volume_metadata_for_ml_thigh_plus.json 



