data:
  # data_dir: standardized_data/challenging_cases/rand_sample/images
  # data_dir: standardized_data/full_thigh_nifti/train/images/OAI_9437407.nii.gz 
  data_dir: standardized_data/challenging_cases/dicom_image_sample/00m/9015402    # dicom folder
  # data_dir: standardized_data/challenging_cases/nifti_image_sample/00m/OAI_9015402.nii.gz  
  mask_labels:
    0: background
    1: sc_fat
    2: fascia
    3: extensors
    4: hamstrings
    5: fem_cortex
    6: fem_bm
    7: adductors
    8: sartorius
    9: gracilis
    10: nv

preprocessing_cfg:
  image_size: 1024
  voxel_num_thre2d: 100
  voxel_num_thre3d: 200
  remove_label_ids: [2]
  instance_bbox: True

device: cuda:0
models:
  obj_det:
    model_path: work_dir/model_weights/finetuned/thighYOLO/best.pt
    model_weights: thighYOLO8_100epoch
    model_type: YOLO
    conf: 0.5
    post_processing: True
  segmentation:
    base_model: work_dir/model_weights/SAM/sam_vit_b_01ec64.pth
    model_path: work_dir/model_weights/finetuned/multiclass_Thigh_SAM/20240522-1945_finetuned_model_best.pth
    model_weights: multiclass_Thigh_SAM
    model_type: vit_b
    trainable:
      prompt_encoder: False
      image_encoder: True
      mask_decoder: True

output_cfg:
  base_output_dir: work_dir/inference
  task_name: OAI_Thigh
  output_ext: nii.gz
  visualize: True
  logging_level: DEBUG