data:
  data_dir: standardized_data/challenging_cases/more_challenging_cases

  mask_labels:
    0: background
    1: sc_fat
    2: fascia
    3: extensors
    4: hamstrings
    5: fem_cortex
    6: fem_bm
    7: adductors
    8: sartorius
    9: gracilis
    10: nv

preprocessing_cfg:
  image_size: 1024
  voxel_num_thre2d: 100
  voxel_num_thre3d: 200
  remove_label_ids: []
  instance_bbox: True   # maybe do again but squeezed?
  make_square: True     # maybe do again but squeezed?
  # sam2:
  #   image_size: 256
  #   image_size: 256

device: cuda:0
models:
  obj_det:
    model_path: /data/mskprojects/mskSAM/users/ghoyer/AutoMedLabel2/work_dir/model_weights/finetuned/thigh/best.pt
    model_weights: thighYOLO8_100epoch_square_resize
    model_type: YOLO
    conf: 0.25
    post_processing: True
  segmentation:
    base_model: work_dir/model_weights/SAM/sam_vit_b_01ec64.pth
    # base_model: work_dir/model_weights/MedSAM/medsam_vit_b.pth
    # base_model: work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt
    
    # model_path: work_dir/finetuning/OAI_Thigh_SAM_YOLO/SAM_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_6/20240706-1605_finetuned_model_best_converted.pth  # had the early stopping of 10 epochs
    model_path: work_dir/model_weights/SAM/sam_vit_b_01ec64.pth
    # model_path: work_dir/model_weights/MedSAM/medsam_vit_b.pth
    # model_path: work_dir/model_weights/SAM2/sam2_hiera_base_plus.pt
    
    # model_weights: multiclass_Thigh_SAM_with_fascia_square_resize
    model_weights: SAM
    # model_weights: MedSAM

    # model_weights: SAM2

    model_type: vit_b
    # model_type: sam2_hiera_b+.yaml

    trainable:
      prompt_encoder: False
      image_encoder: True
      mask_decoder: True


output_cfg:
  base_output_dir: work_dir/inference/thigh_comparison
  task_name: OAI_Thigh
  output_ext: nii.gz
  visualize: True
  logging_level: DEBUG



    # obj_det:
  #   # model_path: work_dir/model_weights/finetuned/thighYOLO/best.pt
  #   model_path: work_dir/obj_detection/runs/detect/train6/weights/best.pt
  #   model_weights: thighYOLO8_100epoch
  #   model_type: YOLO
  #   conf: 0.5
  #   post_processing: True

  # segmentation:
  #   base_model: work_dir/model_weights/SAM/sam_vit_b_01ec64.pth
  #   # model_path: work_dir/model_weights/SAM/sam_vit_b_01ec64.pth
  #   model_path: work_dir/model_weights/finetuned/multiclass_Thigh_SAM/20240522-1945_finetuned_model_best.pth
  #   model_weights: multiclass_Thigh_SAM
  #   # model_weights: SAM
  #   model_type: vit_b
  #   trainable:
  #     prompt_encoder: False
  #     image_encoder: True
  #     mask_decoder: True

  # segmentation:
  #   base_model: work_dir/model_weights/SAM/sam_vit_b_01ec64.pth
  #   model_path: work_dir/finetuning/OAI_Thigh_SAM_YOLO/SAM_full_trainSubjects_sliceBalance_False_imgEnc_True_maskDec_True/Run_3/20240704-1924_finetuned_model_best_converted.pth
  #   model_weights: multiclass_Thigh_SAM_no_fascia
  #   model_type: vit_b
  #   trainable:
  #     prompt_encoder: False
  #     image_encoder: True
  #     mask_decoder: True
