## Verbose Descriptive Baseline Prompting Experimentation Config
## Params for zero_shot_prediction.py:
##     1. Model info
##     2. Input image & prompt info
##     3. Preprocessing info
##     4. Output dir info
##     5. Visualization info

# -------------- Auto-Labeling -------------- #
experiment:
  name: OAI_Thigh_T1_Axial
  description: "Prompt Inference for autolabeling of a dataset via YOLOv8 + SAM."

input_cfg:
  image_path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/full_thigh_nifti/test/images                 
  gt_path: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/full_thigh_nifti/test/masks                   
  path_ext: '.nii.gz'
  ml_metadata_file: /data/VirtualAging/users/ghoyer/correcting_rad_workflow/det2seg/AutoMedLabel/standardized_data/thigh_info/volume_metadata_for_ml.json
  split: 'test' #Optional

preprocessing_cfg:
  image_size: [1024, 512]  # should probably just be 1024
  voxel_num_thre2d: 100
  voxel_num_thre3d: 200
  remove_label_ids: []  # No labels to remove in this configuration 
  target_label_id: null  # No specific label targeted for instance segmentation
  instance_bbox: True
  
  crop_non_zero_slices_flag: False
  bbox_shift: 20
  infer_method: '3D_stepwise' # Options: '3D_stepwise' or '3D_one_step'

device: cuda:0

models:
  obj_det: 
    model_path: 'work_dir/model_weights/finetuned/thighYOLO/best.pt'
    model_weights: 'thighYOLO8'
    model_type: YOLO
  segmentation:
    model_path: 'work_dir/model_weights/finetuned/muscleSAM/20240530-0438_finetuned_model_best.pth'
    model_weights: 'muscleSAM'
    model_type: vit_b
  
base_output_dir: standardized_data/thigh_inference

# --- OUTPUT (OVERRIDE DEFAULT): Location to output labels .txt files
inference_dir: annotations

# --- OUTPUT (OVERRIDE DEFAULT): Location to output (gt, prediction) .npz files
inference_dir: preds

output_configuration:
  save_path: work_dir/prompting/${experiment.name}/Prompt_Summaries
  logging_level: DEBUG 

# # ------------------ VISUALIZE NPY ------------------ #
mask_labels: ${mask_labels} # Optional defined or default in config/datasets/config_fname.yaml

gt_pred_npz_fig_cfg:
  fig_type: ['2D_overlay', 'gif'] # Options: '2D_overlay', 'gif', ['2D_overlay', 'gif']
  num_figs: 5  # Number of files to randomly select and process
  slice_selection: 'with_segmentation' # 'with_segmentation' or 'any'
# --- OUTPUT (OVERRIDE DEFAULT): location to save figures
  fig_path: figs

bbox_prompt_npz_fig_cfg:
  fig_type: ['2D_overlay', 'gif'] # Options: '2D_overlay', 'gif', ['2D_overlay', 'gif']
  num_figs: 5  # Number of files to randomly select and process
  slice_selection: 'with_segmentation' # 'with_segmentation' or 'any'
# --- OUTPUT (OVERRIDE DEFAULT): location to save figures
  fig_path: bbox_prompt_figs





